/** Nombres de icono usados en los datos. El mapa a componentes está en components/ui/icon-map.tsx. */
export type IconName =
  | "droplets"
  | "factory"
  | "ship"
  | "sun"
  | "trending-up"
  | "truck"
  | "handshake"
  | "newspaper"
  | "hard-hat"
  | "shield-check"
  | "ruler"
  | "badge-check"
  | "map-pin"
  | "landmark"
  | "scroll-text"
  | "message-warning"
  | "shield-alert"
  | "wind"
  | "users"
  | "calendar"
  | "file-text"
  | "phone"
  | "mail"
  | "clock";
